

train_config = {
        'host': 'localhost',
        'port': 2000,
        'town': 'Town01',
        'weather': 'ClearNoon',
        'vehicle_model': 'vehicle.tesla.model3',
        'camera_position': [1.5, 0.0, 2.4],
        'camera_rotation': [0.0, 0.0, 0.0],
        'window_width': 800,
        'window_height': 600,
        'target_fps': 20,
        'window_width': 800,
        'window_height': 600,
        'window_title': "CARLA Gym Environment",
        'name_map': 'Town01',
        'set_weather': True,
        'weather_preset': 'ClearNoon',
        'spawn_point': {'x': 383.0, 'y': -2.0, 'z': None, 'yaw': 180.0},
        'goal_point': {'x': 11.71, 'y': -2.0, 'radius': 5.0},
        'random_route_enabled': True,
        'max_random_route_distance': 200.0,
        'min_random_route_distance': 50.0,
        'draw_full_route_each_episode': True,
        'route_draw_life_time': 6.0,
        'route_line_thickness': 0.20,
        'route_draw_all_waypoints': False,
        'route_waypoint_stride': 1,
        'route_waypoint_size': 0.08,
        'route_waypoint_z_offset': 0.7,
        'route_waypoint_color': (255, 255, 0),
        'server_top_camera_enabled': False,
        'camera_fov': 90,
        'camera_position': [-5, 0.0, 2.8],
        'camera_rotation': [-15, 0, 0],
        'throttle_speed': 0.8,
        'brake_speed': 0.5,
        'steer_speed': 0.5,
        'hud_font_size': 20,
        'hud_bg_color': (0, 0, 0, 0),
        'hud_bg_alpha': 128,
        'hud_width': 240,
        'hud_height': 320,
        'enable_photo_capture': True,
        'photo_capture_interval': 1.0,
        'photo_capture_directory': 'run_logs',
        'photo_width': 800,
        'photo_height': 600,
        'photo_fov': 90.0,
        'collision_sensor_enabled': True,
        'lane_invasion_sensor_enabled': True,
        'carla_timeout': 20.0,
    }


config_test = {
        'host': 'localhost',
        'port': 2000,
        'town': 'Town01',
        'weather': 'ClearNoon',
        'vehicle_model': 'vehicle.tesla.model3',
        'camera_position': [1.5, 0.0, 2.4],
        'camera_rotation': [0.0, 0.0, 0.0],
        'target_fps': 20,
        'window_width': 320,
        'window_height': 200,
        'window_title': "CARLA Gym Environment",
        'name_map': 'Town01',
        'set_weather': True,
        'weather_preset': 'ClearNoon',
        'spawn_point': {'x': 383.0, 'y': -2.0, 'z': None, 'yaw': 180.0},
        'goal_point': {'x': 11.71, 'y': -2.0, 'radius': 5.0},
        'random_route_enabled': True,
        'max_random_route_distance': 200.0,
        'min_random_route_distance': 50.0,
        'draw_full_route_each_episode': True,
        'route_draw_life_time': 6.0,
        'route_line_thickness': 0.20,
        'route_draw_all_waypoints': False,
        'route_waypoint_stride': 1,
        'route_waypoint_size': 0.08,
        'route_waypoint_z_offset': 0.7,
        'route_waypoint_color': (255, 255, 0),
        'server_top_camera_enabled': True,
        'server_top_camera_height': 95.0,
        'server_top_camera_pitch': -90.0,
        'server_top_camera_yaw_offset': 0.0,
        'server_top_camera_follow': False,
        'server_top_camera_use_vehicle_yaw': False,
        'server_top_camera_smooth_alpha': 0.2,
        'server_top_camera_autofit_route': True,
        'server_top_camera_fov_deg': 90.0,
        'server_top_camera_margin_m': 25.0,
        'server_top_camera_min_height': 60.0,
        # 'goal_point': {'x': 334.0, 'y': 43.0, 'radius': 5.0},
        'autopilot_mode': True,
        'camera_fov': 90,
        'camera_position': [-5, 0.0, 2.8],
        'camera_rotation': [-15, 0, 0],
        'throttle_speed': 0.8,
        'brake_speed': 0.5,
        'steer_speed': 0.5,
        'hud_font_size': 20,
        'hud_bg_color': (0, 0, 0, 0),
        'hud_bg_alpha': 128,
        'hud_width': 240,
        'hud_height': 320,
        'enable_photo_capture': True,
        'photo_capture_interval': 1.0,
        'photo_capture_directory': 'run_logs',
        'photo_width': 320,
        'photo_height': 200,
        'photo_fov': 90.0,
        'collision_sensor_enabled': True,
        'lane_invasion_sensor_enabled': True,
        'carla_timeout': 20.0,
    }  # Placeholder for actual configuration